### ISSUE TITLE
Incorrect Output Path

### ISSUE THREAD

**Issue by masakinihirota** [locize/i18next-typescript-examples#1]
## 🐛 Bug Report

The output path is wrong

## To Reproduce

```terminal
gh repo clone locize/i18next-typescript-examples
cd i18next-typescript-examples
cd 1
pnpm i
pnpm run start

```

This works fine

```terminal
pnpm run toc

```

↓output result

```i18next-typescript-examples\1\@types\resources.ts
import fallback from '..\..\locales\en\fallback.json';
import ns1 from '..\..\locales\en\ns1.json';
import ns2 from '..\..\locales\en\ns2.json';

const resources = {
  fallback,
  ns1,
  ns2
} as const;

export default resources;

``````

The path is wrong like this

## Expected behavior

```i18next-typescript-examples\1\@types\resources.ts
import fallback from "../locales/en/fallback.json"
import ns1 from "../locales/en/ns1.json"
import ns2 from "../locales/en/ns2.json"

const resources = {
  fallback,
  ns1,
  ns2,
} as const

export default resources

```

## Your Environment

- *runtime version*: i.e. node v14, deno, browser xy
- *module version*: >=19.0.0
- *os*: Mac, Windows, Linux
- *any other relevant information*

node -v
v18.17.1

windows 10

**Comment by adrai** [comment]
Sorry, I have no windows environment... can you try with i18next-resources-for-ts v1.3.1 ?

**Comment by masakinihirota** [comment]
```package.json

  "devDependencies": {
    "i18next-resources-for-ts": "1.3.1",
    "typescript": "^5.2.2"
  },
...
```
↑ 1.3.0-> 1.3.1

↓ pnpm up

```
09-07 08:13:00> pnpm up
Packages: +1 -1
+-
Progress: resolved 5, reused 5, downloaded 0, added 0, done

devDependencies:
- i18next-resources-for-ts 1.3.0
+ i18next-resources-for-ts 1.3.1

Done in 1.4s
```

↓file delete
@types\resources.ts

`pnpm toc`

```terminal
09-07 08:08:21> pnpm toc

> example1@1.0.0 toc C:\*****\i18n_typescript\variousexamples\1
> i18next-resources-for-ts toc -i ./locales/en -o ./@types/resources.ts

created toc resources file for 3 namespaces: C:\*****\i18n_typescript\variousexamples\1\@types\resources.ts

```

↓create 

```@types\resources.ts
import fallback from '..\..\locales\en\fallback.json';
import ns1 from '..\..\locales\en\ns1.json';
import ns2 from '..\..\locales\en\ns2.json';

const resources = {
  fallback,
  ns1,
  ns2
} as const;

export default resources;

```

↓ VSCode save

```@types\resources.ts
import fallback from "....localesen\fallback.json"
import ns1 from "....localesen\ns1.json"
import ns2 from "....localesen\ns2.json"

const resources = {
  fallback,
  ns1,
  ns2,
} as const

export default resources

```

I haven't used Prettier or ESLint, but when I saved @types\resources.ts, the above changes were made VSCode

**Comment by adrai** [comment]
Sorry, but we can't influence VSCode... you need to investigate yourself.

**Comment by masakinihirota** [comment]
use
"i18next-resources-for-ts": "1.3.1",
↓

correct path
```correct path
import fallback from '..\..\locales\en\fallback.json';
import ns1 from '..\..\locales\en\ns1.json';
import ns2 from '..\..\locales\en\ns2.json';

```

expect
```expect
import fallback from "../locales/en/fallback.json"
import ns1 from "../locales/en/ns1.json"
import ns2 from "../locales/en/ns2.json"

```

There are two issues. 

"..\..\" is not the correct path

that the delimiter is output as "\\"
I think this should be "/"

**Comment by adrai** [comment]
Can you try with i18next-resources-for-ts v1.3.2 ?

**Comment by masakinihirota** [comment]
```package.json
   "i18next-resources-for-ts": "1.3.2",
...
```

reinstall

terminal

```
pnpm start

```

↑ expect success

next

rename & move original file 
@types\resources.ts
↓
rename @types\resources._

terminal
```terminal
pnpm toc

```

↓output

![output](https://github.com/locize/i18next-typescript-examples/assets/7696510/e0977381-985f-4ede-a898-c92c55d3de6a)

output left
>pnpm toc

output right 
>original


ok path char
unexpected depth of path

**Comment by adrai** [comment]
ok, v1.3.3 should work for windows

**Comment by masakinihirota** [comment]
delete file @types\resources.ts

package.json

```
    "i18next-resources-for-ts": "1.3.3",
...

```

↓

![output2](https://github.com/locize/i18next-typescript-examples/assets/7696510/837d998a-bf03-4408-ba63-85c1d18df1ae)

I compared the files and found a match.

It worked as expected, thank you so much.
